version: '3.1'

services:
  mysql: 
    image: mysql:8.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  node:
    image: node:21.3
    working_dir: /usr/app
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    

  nginx:
    image: nginx:1.25
    volumes:
    - ./html:/usr/share/nginx/html
    ports:
    - "8080:80"
