version: '3.1'

services:
  mysql: 
    image: mysql:8.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: dbase
    volumes:
      - ./mysql:/var/lib/mysql

  node:
    image: node:21.3
    working_dir: /usr/app
    command: npm start
    volumes:
      - ./node:/usr/app

  nginx:
    image: nginx:1.25
    depends_on:
      - node
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
